# Generated by Django 4.0 on 2021-12-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_waiting',
            field=models.BooleanField(default=True),
        ),
    ]
