# Generated by Django 4.0 on 2021-12-16 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_game_player_alter_game_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='is_waiting',
        ),
        migrations.RemoveField(
            model_name='game',
            name='map_created',
        ),
    ]
