# Generated by Django 4.0 on 2021-12-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_remove_game_is_waiting_remove_game_map_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_waiting',
            field=models.BooleanField(default=True),
        ),
    ]
