# Generated by Django 4.0 on 2021-12-16 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_game_is_waiting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='player',
            new_name='opponent',
        ),
    ]
