# Generated by Django 4.0 on 2021-12-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_rename_player_game_opponent'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='map_created',
            field=models.BooleanField(default=False),
        ),
    ]
